# Generated by Django 2.2.3 on 2019-11-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eval',
            name='maxn',
        ),
        migrations.RemoveField(
            model_name='eval',
            name='minn',
        ),
    ]
