# Generated by Django 2.2.3 on 2019-10-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='desig',
            new_name='design',
        ),
    ]
