# Generated by Django 2.2.3 on 2019-10-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0002_auto_20191029_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='design',
            new_name='desig',
        ),
    ]
