# Generated by Django 2.2.3 on 2019-10-31 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0004_auto_20191030_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designn',
            new_name='design',
        ),
    ]
