# Generated by Django 2.2.3 on 2019-10-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=120)),
                ('cat', models.CharField(max_length=120)),
                ('pri', models.IntegerField()),
                ('spe', models.CharField(max_length=120)),
            ],
        ),
    ]
