# Generated by Django 2.2.3 on 2019-11-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cid', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=120)),
                ('u_bch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.Batch')),
                ('u_cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=120)),
                ('f_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.Batch')),
                ('f_cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.Course')),
                ('f_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='b_cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.Course'),
        ),
    ]
