# Generated by Django 2.2.3 on 2019-11-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='f_batch',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='f_cname',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_bch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_cname',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
