# Generated by Django 2.2.3 on 2019-11-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0003_auto_20191108_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_bch',
            new_name='Batch_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_cname',
            new_name='Course_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='Phone',
        ),
    ]
