# Generated by Django 2.2.3 on 2019-11-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0004_auto_20191108_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='hell', max_length=120),
            preserve_default=False,
        ),
    ]
